FROM mysql

ENV MYSQL_USER=hong
ENV MYSQL_PASSWORD=hong1234
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=hongdb

CMD [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]